package dev.zomboid.scavenging;
import java.util.*;import net.minecraft.core.*;import net.minecraft.nbt.CompoundTag;import net.minecraft.world.item.*;import net.minecraft.world.level.*;import net.minecraft.world.level.block.*;import net.minecraft.world.level.block.state.*;import net.minecraft.world.level.block.entity.*;import net.minecraft.world.entity.player.*;import net.minecraft.server.level.ServerPlayer;import net.minecraft.world.*;import net.minecraft.core.registries.BuiltInRegistries;
public final class BehaviorChecks {
 static int cases;static void check(boolean ok){cases++;if(!ok)throw new AssertionError("behavior "+cases);}
 public static class Container {final ItemStack[] slots;Container(int n){slots=new ItemStack[n];Arrays.fill(slots,ItemStack.EMPTY);}public int getContainerSize(){return slots.length;}public ItemStack getItem(int i){return slots[i];}public void setItem(int i,ItemStack s){slots[i]=s;}public void setChanged(){}}
 public static class Handler {final Container c=new Container(2);public int getSlots(){return 2;}public ItemStack getStackInSlot(int i){return c.getItem(i);}public void setStackInSlot(int i,ItemStack s){c.setItem(i,s);}public ItemStack insertItem(int i,ItemStack s,boolean simulate){if(!c.getItem(i).isEmpty())return s;int n=Math.min(3,s.getCount());c.setItem(i,s.copyWithCount(n));ItemStack left=s.copy();left.shrink(n);return left;}}
 public static class WaterState extends BlockState {final int amount;WaterState(Block block,int amount){super(block);this.amount=amount;}public List<Prop> getProperties(){return List.of(new Prop());}public int getValue(Prop p){return amount;}public WaterState setValue(Prop p,Integer value){return new WaterState(getBlock(),value);}}
 public static class Prop {public String getName(){return "level";}}
 public static class Chest extends ChestBlockEntity {World owner;public Level getLevel(){return owner;}public BlockPos getBlockPos(){return owner.pos;}final Container c=new Container(27);public int getContainerSize(){return c.getContainerSize();}public ItemStack getItem(int n){return c.getItem(n);}public void setItem(int n,ItemStack s){c.setItem(n,s);}public Object getCustomName(){return null;}}
 public static class Random {public double nextDouble(){return .5;}}
 public static class World extends Level {BlockState state;final BlockPos pos=new BlockPos(0,0,0);final Chest chest=new Chest();public World(BlockState s){state=s;chest.owner=this;}public BlockState getBlockState(BlockPos p){return state;}@Override public BlockEntity getBlockEntity(BlockPos p){return chest;}@Override public boolean hasChunkAt(BlockPos p){return true;}public boolean setBlock(BlockPos p,BlockState s,int flags){state=s;return true;}}
 public static class Person extends ServerPlayer {public Object inventoryMenu=new Object(),containerMenu=inventoryMenu;public int hurtTime;public Mode gameMode=new Mode(this);final UUID id=UUID.randomUUID();double x;boolean sneak;public Person(World l){setLevel(l);}public UUID getUUID(){return id;}public double getX(){return x;}public double getY(){return 0;}public double getZ(){return 0;}public boolean isAlive(){return true;}public boolean isSpectator(){return false;}public boolean isCreative(){return getAbilities().instabuild;}public double getLuck(){return 0;}public Random getRandom(){return new Random();}public boolean isShiftKeyDown(){return sneak;}public void setShiftKeyDown(boolean value){sneak=value;}public ItemStack getMainHandItem(){return getItemInHand(InteractionHand.MAIN_HAND);}public double blockInteractionRange(){return 5;}public double distanceToSqr(double a,double b,double c){return (x-a)*(x-a)+b*b+c*c;}public boolean mayInteract(Level l,BlockPos p){return true;}}
 public static class Mode {final Person p;int opens;public Mode(Person p){this.p=p;}public InteractionResult useItemOn(Person p,Object level,Object stack,Object hand,Object hit){check(Search.replaying());opens++;p.containerMenu=new Object();return InteractionResult.SUCCESS;}}
 public static class Event extends net.neoforged.neoforge.event.entity.player.PlayerInteractEvent.RightClickBlock {final Person p;final World world;boolean canceled;Event(Person p){this.p=p;world=(World)p.level();}public Person getEntity(){return p;}public World getLevel(){return world;}public BlockPos getPos(){return world.pos;}public Object getHitVec(){return new Object();}public InteractionHand getHand(){return InteractionHand.MAIN_HAND;}public ItemStack getItemStack(){return p.getMainHandItem();}public void setCanceled(boolean value){canceled=value;}public void setCancellationResult(InteractionResult value){}}
 public static class Accessor {final Object object;Accessor(Object o){object=o;}public Object getTarget(){return object;}}
 static void ticks(World l,int n){for(int i=0;i<n;i++){l.advance();Search.tick();}}
 public static void main(String[] args){
 Container c=new Container(2);c.setItem(0,new ItemStack(62,0,"iron",false));Loot.Inv inv=new Loot.Inv(c,0);ItemStack input=new ItemStack(5,0,"iron",false);ItemStack left=(ItemStack)inv.add(input);check(left.isEmpty()&&c.getItem(0).getCount()==64&&c.getItem(1).getCount()==3);check(input.getCount()==5);List<Object> snapshot=inv.copy();inv.clear();check(c.getItem(0).isEmpty()&&((ItemStack)snapshot.get(0)).getCount()==64);for(int i=0;i<snapshot.size();i++)inv.set(i,snapshot.get(i));check(c.getItem(1).getCount()==3);
 Container full=new Container(1);full.setItem(0,new ItemStack(64,0,"iron",false));check(((ItemStack)new Loot.Inv(full,0).add(input)).getCount()==5);
 Handler handler=new Handler();check(((ItemStack)new Loot.Inv(handler,1).add(new ItemStack(8,0,"iron",false))).getCount()==2);check(handler.c.getItem(0).getCount()+handler.c.getItem(1).getCount()==6);
 List<Object> additional=new ArrayList<>();new Loot.Inv(additional,2).add(new ItemStack(130,0,"iron",false));check(additional.size()==3&&((ItemStack)additional.get(2)).getCount()==2);
 check(((ItemStack)new Loot.Inv(List.of(),2).add(input)).getCount()==5);
 History history=new History();history.mark("corpse:123:5",3);CompoundTag saved=history.save(new CompoundTag(),null);History loaded=History.load(saved,null);check(loaded.has("corpse:123:5")&&loaded.tier("corpse:123:5")==3);check(!loaded.has("corpse:123:6"));
 Block barrel=new Block();BuiltInRegistries.BLOCK.put("minecraft:barrel",barrel);BuiltInRegistries.SOUND_EVENT.put("item.bundle.insert",new net.minecraft.sounds.SoundEvent());World world=new World(new BlockState(barrel));Person p=new Person(world);Event e=new Event(p);check(Search.hidePreview(new Accessor(world.chest)));Search.event(e);check(e.canceled&&Search.jobs.size()==1);Search.event(new Event(p));check(Search.jobs.size()==1);ticks(world,29);check(p.gameMode.opens==0);world.chest.getPersistentData().putBoolean("ScavengingOpened",true);ticks(world,1);check(p.gameMode.opens==1&&Search.jobs.isEmpty());
 p.containerMenu=p.inventoryMenu;world.chest.getPersistentData().putBoolean("ScavengingOpened",false);Search.event(new Event(p));p.x=1;ticks(world,1);check(Search.jobs.isEmpty()&&p.gameMode.opens==1);p.x=0;Search.event(new Event(p));p.hurtTime=1;ticks(world,1);check(Search.jobs.isEmpty());p.hurtTime=0;Search.event(new Event(p));p.containerMenu=new Object();ticks(world,1);check(Search.jobs.isEmpty());check(Search.warned.isEmpty());Search.clear();
 p.containerMenu=p.inventoryMenu;world.chest.getPersistentData().putBoolean("ScavengingOpened",false);BuiltInRegistries.ITEM.put("minecraft:string",new Item("minecraft:string"));BuiltInRegistries.SOUND_EVENT.put("item.bundle.remove_one",new net.minecraft.sounds.SoundEvent());Search.event(new Event(p));ticks(world,30);check(Search.jobs.isEmpty()&&world.chest.getPersistentData().getBoolean("ScavengingOpened"));check(world.chest.c.getItem(0).getCount()==1);check(!Search.hidePreview(new Accessor(world.chest)));check(dev.survivorcreator.skills.Skills.awarded==8);p.containerMenu=p.inventoryMenu;Event reopened=new Event(p);Search.event(reopened);check(!reopened.canceled&&Search.jobs.isEmpty()&&dev.survivorcreator.skills.Skills.awarded==8);check(Search.warned.isEmpty());
 Block water=new Block(),empty=new Block();BuiltInRegistries.BLOCK.put("minecraft:water_cauldron",water);BuiltInRegistries.BLOCK.put("minecraft:cauldron",empty);
 // defaultBlockState belongs to a real Block in game; this fake exercises 3 -> 2 only.
 World source=new World(new WaterState(water,3));Person drinker=new Person(source);drinker.setItemInHand(InteractionHand.MAIN_HAND,new ItemStack(dev.zomboid.survival.Survival.EMPTY.get()));Event refill=new Event(drinker);dev.zomboid.survival.WaterSources.fill(refill);check(refill.canceled&&((WaterState)source.state).amount==2);check(drinker.getMainHandItem().is(dev.zomboid.survival.Survival.WATER.get()));
 World plain=new World(new BlockState(barrel));Person unfilled=new Person(plain);unfilled.setItemInHand(InteractionHand.MAIN_HAND,new ItemStack(dev.zomboid.survival.Survival.EMPTY.get()));Event ignored=new Event(unfilled);dev.zomboid.survival.WaterSources.fill(ignored);check(!ignored.canceled&&unfilled.getMainHandItem().is(dev.zomboid.survival.Survival.EMPTY.get()));
 check(dev.zomboid.survival.WaterItems.PURIFIED.water==8&&dev.zomboid.survival.WaterItems.MINERAL.water==10);
 System.out.println(cases+" simulated inventory/history/search/water behavior cases passed; not Minecraft");}
}
