package dev.zomboid.scavenging;
import java.util.*;
public final class Loot {
 static final String[] BASIC={"minecraft:apple","minecraft:bread","minecraft:torch","minecraft:coal","minecraft:string","minecraft:iron_nugget","minecraft:leather","zomboid_survival:water_bottle"};
 static final String[] MATERIAL={"minecraft:coal","minecraft:raw_iron","minecraft:raw_copper","minecraft:iron_ingot","minecraft:copper_ingot","minecraft:leather"};
 static final String[] GOOD={"minecraft:iron_ingot","minecraft:gold_ingot","minecraft:redstone","minecraft:lapis_lazuli","minecraft:iron_pickaxe","minecraft:iron_axe","zomboid_survival:purified_water"};
 static final String[] PREMIUM={"minecraft:diamond","minecraft:emerald","minecraft:golden_apple","minecraft:diamond_pickaxe","minecraft:diamond_axe","zomboid_survival:mineral_water"};
 static Object registry(String name){return R.get(R.type("net.minecraft.core.registries.BuiltInRegistries"),name);}
 static Object id(String id){return R.call(R.type("net.minecraft.resources.ResourceLocation"),"parse",id);}
 static Object stack(String id,int count){Object reg=registry("ITEM");Object item=R.call(reg,"get",id(id));if(item==null||R.call(reg,"getKey",item).toString().equals("minecraft:air"))return R.get(R.type("net.minecraft.world.item.ItemStack"),"EMPTY");return R.make("net.minecraft.world.item.ItemStack",item,count);}
 static Inv inventory(Search.Target t){if(t.corpse!=null)return new Inv(R.get(t.corpse,"inventory"),0);if(t.entity!=null)return new Inv(R.call(R.call(t.entity,"getDeath"),"getAdditionalItems"),2);if(Search.is(t.be,"net.p3pp3rf1y.sophisticatedstorage.block.StorageBlockEntity"))return new Inv(R.call(R.call(t.be,"getStorageWrapper"),"getInventoryHandler"),1);return new Inv(t.be,0);}
 static String category(Search.Target t){if(t.corpse!=null||t.entity!=null)return "corpse";try{Object custom=R.call(t.be,"getCustomName");return (t.hint+" "+(custom==null?"":R.call(custom,"getString"))).toLowerCase(Locale.ROOT);}catch(RuntimeException e){return t.hint.toLowerCase(Locale.ROOT);}}
 static String choose(Object p,String[] pool){return pool[(int)(Search.random(p)*pool.length)];}
 static String themed(String category,int tier,Object player){if(category.contains("med")||category.contains("pharm")||category.contains("clinic")||category.contains("office")||category.contains("cabinet")){String[] pool={"minecraft:paper","minecraft:honey_bottle","zomboid_survival:water_bottle","firstaid:bandage","zomboid_survival:purified_water","minecraft:bread"};String s=choose(player,pool);Object v=stack(s,1);if(R.yes(R.call(v,"isEmpty")))return "minecraft:honey_bottle";return s;}
 if(category.contains("tool")||category.contains("garage")||category.contains("workshop")||category.contains("nuclear"))return choose(player,tier>=3?PREMIUM:tier>=2?GOOD:MATERIAL);
 if(category.contains("food")||category.contains("kitchen")||category.contains("market")||category.contains("drink")||category.contains("fridge"))return choose(player,new String[]{"minecraft:bread","minecraft:apple","minecraft:baked_potato","zomboid_survival:water_bottle","zomboid_survival:cola","zomboid_survival:orange_soda","zomboid_survival:mineral_water"});
 return choose(player,tier>=3?PREMIUM:tier>=2?GOOD:BASIC);}
 static void bonus(Search.Target t,Object p,int tier,int level){Inv inv=inventory(t);String category=category(t);boolean body=category.equals("corpse");if(body){if(Search.random(p)<.70)insert(inv,stack(choose(p,MATERIAL),1+(int)(Search.random(p)*(2+tier))),t,p);if(Search.random(p)<.60)insert(inv,stack("minecraft:leather",1+(int)(Search.random(p)*3)),t,p);if(Search.random(p)<.45)insert(inv,stack(choose(p,new String[]{"zomboid_survival:water_bottle","zomboid_survival:mineral_water","zomboid_survival:cola","zomboid_survival:orange_soda"}),1),t,p);}
 for(int i=0;i<Rules.bonusRolls(tier,level);i++){Object s=stack(themed(category,tier,p),1+Rules.quantityBonus(level)+(tier==0?0:(int)(Search.random(p)*(1+tier))));if(R.yes(R.call(s,"isDamageableItem")))R.call(s,"setDamageValue",(int)(R.num(R.call(s,"getMaxDamage"))*Rules.wear(tier,level)));insert(inv,s,t,p);}inv.changed();}
 static void insert(Inv inv,Object stack,Search.Target t,Object player){Object remaining=inv.add(stack);if(!R.yes(R.call(remaining,"isEmpty")))R.call(player,"drop",remaining,false);}
 static boolean upgrade(Search.Job j,int tier){Search.Target t=j.target;if(Search.is(t.be,"net.p3pp3rf1y.sophisticatedstorage.block.StorageBlockEntity"))return resize(j,tier);String block=Search.blockId(t.level,t.pos);if(!Set.of("minecraft:chest","minecraft:trapped_chest","minecraft:barrel").contains(block))return false;
 Object state=R.call(t.level,"getBlockState",t.pos);
 if(Search.is(t.be,"net.minecraft.world.level.block.entity.BaseContainerBlockEntity")&&R.get(t.be,"lockKey")!=R.get(R.type("net.minecraft.world.LockCode"),"NO_LOCK"))return false;
 // Convert only the clicked half. Neighbor updates make the other half a single chest, keeping its inventory untouched.
 int baseCapacity=inventory(t).size();for(Object prop:(Iterable<?>)R.call(state,"getProperties"))if(R.call(prop,"getName").equals("type")&&!R.call(R.call(state,"getValue",prop),"getSerializedName").equals("single"))baseCapacity=Math.max(baseCapacity,54);
 String name=tier>=4?"diamond_barrel":tier>=3?"gold_barrel":tier>=2?"iron_barrel":"copper_barrel";Object reg=registry("BLOCK"),newBlock=R.call(reg,"get",id("sophisticatedstorage:"+name));if(newBlock==null||R.call(reg,"getKey",newBlock).toString().equals("minecraft:air"))return false;
 Inv old=inventory(t);List<Object> saved=old.copy();Object oldNbt=R.call(t.be,"saveWithFullMetadata",R.call(t.level,"registryAccess"));Object custom=R.call(t.be,"getCustomName");R.call(j.player,"closeContainer");
 try {old.clear();if(!R.yes(R.call(t.level,"setBlock",t.pos,R.call(newBlock,"defaultBlockState"),3)))throw new IllegalStateException("Storage replacement rejected");Object be=R.call(t.level,"getBlockEntity",t.pos);Search.Target next=new Search.Target(t.level,t.pos,be,null,null,"upgraded");Inv fresh=inventory(next);grow(be,Math.max(Rules.slots(tier),baseCapacity+27*tier));fresh=inventory(next);if(fresh.size()<saved.size())throw new IllegalStateException("Storage too small");for(int i=0;i<saved.size();i++)fresh.set(i,saved.get(i));if(custom!=null)R.call(be,"setCustomName",custom);Search.mark(next,tier);fresh.changed();Search.sound(next,"BLOCK_AMETHYST_BLOCK_CHIME",.7f);Search.message(j.player,"¡Hallazgo "+Rules.name(tier)+"! Barril ampliado");Search.open(new Search.Job(j.player,next,j.hit,0,j.skill));return true;
 }catch(Throwable e){try{Object current=R.call(t.level,"getBlockEntity",t.pos);if(current!=null&&Search.is(current,"net.p3pp3rf1y.sophisticatedstorage.block.StorageBlockEntity"))inventory(new Search.Target(t.level,t.pos,current,null,null,"rollback")).clear();R.call(t.level,"setBlock",t.pos,state,3);Object restored=R.call(t.level,"getBlockEntity",t.pos);R.call(restored,"loadWithComponents",oldNbt,R.call(t.level,"registryAccess"));R.call(restored,"setChanged");Search.open(new Search.Job(j.player,new Search.Target(t.level,t.pos,restored,null,null,t.key),j.hit,0,j.skill));}catch(Throwable restore){e.addSuppressed(restore);}Search.warn("storage conversion rollback",e);return false;}}
 static void grow(Object be,int minimum){Object wrapper=R.call(be,"getStorageWrapper");Object handler=R.call(wrapper,"getInventoryHandler");int size=((Number)R.call(handler,"getSlots")).intValue();if(size<minimum){R.call(be,"changeStorageSize",minimum-size,0);R.call(be,"setChanged");}if(((Number)R.call(R.call(wrapper,"getInventoryHandler"),"getSlots")).intValue()<minimum)throw new IllegalStateException("Storage expansion rejected");}
 static boolean resize(Search.Job j,int tier){Object be=j.target.be;int old=inventory(j.target).size();R.call(j.player,"closeContainer");try{grow(be,Math.max(Rules.slots(tier),old+27*tier));Search.mark(j.target,tier);Search.open(j);Search.message(j.player,"¡Hallazgo "+Rules.name(tier)+"! "+inventory(j.target).size()+" espacios");return true;}catch(Throwable e){Search.warn("storage expansion",e);Search.open(j);return false;}}
 static final class Inv {final Object value;final int kind;Inv(Object o,int k){value=o;kind=k;}int size(){return kind==2?((List<?>)value).size():((Number)R.call(value,kind==0?"getContainerSize":"getSlots")).intValue();}Object get(int i){return kind==2?((List<?>)value).get(i):R.call(value,kind==0?"getItem":"getStackInSlot",i);} @SuppressWarnings("unchecked")void set(int i,Object s){if(kind==2)((List<Object>)value).set(i,s);else R.call(value,kind==0?"setItem":"setStackInSlot",i,s);}void changed(){if(kind==0)R.call(value,"setChanged");}void clear(){for(int i=0;i<size();i++)set(i,R.get(R.type("net.minecraft.world.item.ItemStack"),"EMPTY"));}List<Object> copy(){List<Object> out=new ArrayList<>();for(int i=0;i<size();i++)out.add(R.call(get(i),"copy"));return out;}
 Object add(Object stack){Object remaining=R.call(stack,"copy");if(R.yes(R.call(remaining,"isEmpty")))return remaining;if(kind==1){for(int i=0;i<size();i++){remaining=R.call(value,"insertItem",i,remaining,false);if(R.yes(R.call(remaining,"isEmpty")))break;}return remaining;}
 for(int i=0;i<size();i++){Object old=get(i);if(R.yes(R.call(old,"isEmpty")))continue;if(R.yes(R.call(R.type("net.minecraft.world.item.ItemStack"),"isSameItemSameComponents",old,remaining))){int n=Math.min(((Number)R.call(old,"getMaxStackSize")).intValue()-((Number)R.call(old,"getCount")).intValue(),((Number)R.call(remaining,"getCount")).intValue());if(n>0){R.call(old,"grow",n);R.call(remaining,"shrink",n);}}if(R.yes(R.call(remaining,"isEmpty")))return remaining;}
 for(int i=0;i<size();i++)if(R.yes(R.call(get(i),"isEmpty"))){int n=Math.min(((Number)R.call(remaining,"getMaxStackSize")).intValue(),((Number)R.call(remaining,"getCount")).intValue());set(i,R.call(remaining,"copyWithCount",n));R.call(remaining,"shrink",n);if(R.yes(R.call(remaining,"isEmpty")))return remaining;}
 if(kind==2){@SuppressWarnings("unchecked")List<Object> list=(List<Object>)value;while(!R.yes(R.call(remaining,"isEmpty"))){int n=Math.min(((Number)R.call(remaining,"getMaxStackSize")).intValue(),((Number)R.call(remaining,"getCount")).intValue());try{list.add(R.call(remaining,"copyWithCount",n));}catch(UnsupportedOperationException fixed){return remaining;}R.call(remaining,"shrink",n);}}return remaining;}
 }
}
