package dev.zomboid.scavenging;
import java.util.*;
public final class Search {
 static final Map<UUID,Job> jobs=new HashMap<>();
 static final ThreadLocal<Boolean> replay=ThreadLocal.withInitial(()->false);
 static final Set<String> warned=new HashSet<>();
 public static boolean replaying(){return replay.get();}
 static void warn(String where,Throwable e){if(warned.add(where)){System.err.println("[Scavenging] "+where);e.printStackTrace();}}
 static Object type(String name){return R.type(name);}static boolean is(Object o,String name){try{return R.type(name).isInstance(o);}catch(RuntimeException e){return false;}}
 static Object level(Object p){return R.call(p,"level");}static long now(Object l){return R.lng(R.call(l,"getGameTime"));}
 static UUID uuid(Object p){return (UUID)R.call(p,"getUUID");}
 static boolean client(Object l){return R.yes(R.get(l,"isClientSide"));}
 static Object text(String s){return R.call(type("net.minecraft.network.chat.Component"),"literal",s);}
 static void message(Object p,String s){R.call(p,"displayClientMessage",text(s),true);}
 static Object main(){return R.get(type("net.minecraft.world.InteractionHand"),"MAIN_HAND");}
 static Object tag(Object be){return R.call(be,"getPersistentData");}
 static int skill(Object p){try{Object skills=type("dev.survivorcreator.skills.Skills"),s=R.call(skills,"get","scavenging");return s==null?0:((Number)R.call(skills,"level",p,s)).intValue();}catch(Throwable e){warn("skill",e);return 0;}}
 static double luck(Object p){return R.num(R.call(p,"getLuck"));}
 static boolean eligible(Object p){return is(p,"net.minecraft.server.level.ServerPlayer")&&!R.yes(R.call(p,"isSpectator"))&&R.yes(R.call(p,"isAlive"));}
 static boolean fresh(Target t){if(t.be!=null){if(is(t.be,"net.minecraft.world.RandomizableContainer")&&R.call(t.be,"getLootTable")!=null)return true;return !R.yes(R.call(tag(t.be),"getBoolean","ScavengingOpened"));}return !History.get(t.level).has(t.key);}
 static void mark(Target t,int tier){if(t.be!=null){R.call(tag(t.be),"putBoolean","ScavengingOpened",true);R.call(tag(t.be),"putInt","ScavengingRarity",tier);R.call(t.be,"setChanged");
 if(is(t.be,"net.minecraft.world.level.block.entity.ChestBlockEntity")){Object state=R.call(t.level,"getBlockState",t.pos);Object container=R.call(type("net.minecraft.world.level.block.ChestBlock"),"getContainer",R.call(state,"getBlock"),state,t.level,t.pos,false);if(is(container,"net.minecraft.world.CompoundContainer")){for(String field:List.of("container1","container2")){Object half=R.get(container,field);if(is(half,"net.minecraft.world.level.block.entity.BlockEntity")){R.call(tag(half),"putBoolean","ScavengingOpened",true);R.call(tag(half),"putInt","ScavengingRarity",tier);R.call(half,"setChanged");}}}}
 }else History.get(t.level).mark(t.key,tier);}
 static Object corpse(Object l,Object pos){try{Object data=R.call(type("dev.zomboid.remains.ZombieRemainsLoot"),"data",l);return ((Map<?,?>)R.get(data,"corpses")).get(R.lng(R.call(pos,"asLong")));}catch(Throwable e){return null;}}
 static String blockId(Object l,Object pos){Object b=R.call(R.call(l,"getBlockState",pos),"getBlock");return R.call(R.get(type("net.minecraft.core.registries.BuiltInRegistries"),"BLOCK"),"getKey",b).toString();}
 static Target target(Object l,Object pos){Object be=R.call(l,"getBlockEntity",pos);String id=blockId(l,pos);if(be!=null&&(is(be,"net.minecraft.world.level.block.entity.ChestBlockEntity")||is(be,"net.minecraft.world.level.block.entity.BarrelBlockEntity")||is(be,"net.p3pp3rf1y.sophisticatedstorage.block.StorageBlockEntity")))return new Target(l,pos,be,null,null,id+":"+R.call(pos,"asLong"));
  if(id.startsWith("doomsday_decoration:remains_")||id.equals("zombie_remains_loot:skeletal_remains")){Object corpse=corpse(l,pos);if(corpse!=null&&!R.yes(R.get(corpse,"skeleton")))return new Target(l,pos,null,corpse,null,"corpse:"+R.call(pos,"asLong")+":"+R.get(corpse,"born"));}return null;}
 static Target entityTarget(Object e){String n=e.getClass().getName();if(!n.equals("de.maxhenkel.corpse.entities.CorpseEntity"))return null;if(R.yes(R.call(e,"isRemoved")))return null;return new Target(level(e),R.call(e,"blockPosition"),null,null,e,"entity:"+uuid(e));}
 public static void event(Object e){if(replaying())return;try{Object p=R.call(e,"getEntity"),l=R.call(e,"getLevel");if(client(l)||!eligible(p)||R.call(e,"getHand")!=main())return;Target t=target(l,R.call(e,"getPos"));if(t==null||!fresh(t))return;if(t.corpse!=null&&R.yes(R.call(type("dev.zomboid.remains.ZombieRemainsLoot"),"blade",R.call(p,"getMainHandItem"))))return;cancel(e);start(p,t,R.call(e,"getHitVec"));}catch(Throwable x){warn("block interaction",x);}}
 public static void entityEvent(Object e){if(replaying())return;try{Object p=R.call(e,"getEntity");if(client(level(p))||!eligible(p)||R.call(e,"getHand")!=main())return;Target t=entityTarget(R.call(e,"getTarget"));if(t==null||!fresh(t))return;cancel(e);start(p,t,null);}catch(Throwable x){warn("entity interaction",x);}}
 static void cancel(Object event){R.call(event,"setCancellationResult",R.get(type("net.minecraft.world.InteractionResult"),"SUCCESS"));R.call(event,"setCanceled",true);}
 public static boolean shift(Object p,Object pos){if(replaying())return false;try{Target t=target(level(p),pos);if(t==null)return false;Object v=R.call(type("net.minecraft.world.phys.Vec3"),"atCenterOf",pos);Object hit=R.make("net.minecraft.world.phys.BlockHitResult",v,R.get(type("net.minecraft.core.Direction"),"UP"),pos,false);if(fresh(t))start(p,t,hit);else open(new Job(p,t,hit,0,skill(p)));return true;}catch(Throwable e){warn("silent search",e);return false;}}
 static void start(Object p,Target t,Object hit){if(R.get(p,"containerMenu")!=R.get(p,"inventoryMenu"))return;Job current=jobs.get(uuid(p));if(current!=null&&current.target.same(t))return;Job j=new Job(p,t,hit,now(t.level),skill(p));jobs.put(uuid(p),j);sound(t,"ITEM_BUNDLE_INSERT",.55f);message(p,"Buscando 0% · Scavenging "+j.skill);}
 public static boolean hidePreview(Object accessor){try{Object object=R.call(accessor,"getTarget");if(object==null)return false;Target t=null;if(is(object,"net.minecraft.world.level.block.entity.BlockEntity")){Object l=R.call(object,"getLevel");if(l!=null&&!client(l))t=target(l,R.call(object,"getBlockPos"));}else if(object.getClass().getName().equals("de.maxhenkel.corpse.entities.CorpseEntity")&&!client(level(object)))t=entityTarget(object);return t!=null&&fresh(t);}catch(Throwable e){warn("inventory preview",e);return true;}}
 public static String preview(Object object,Object player){
 try{Object interaction=type("cn.kafei.interact.Interaction");if(!R.yes(R.call(interaction,"allowed",object,player)))return "Contenido protegido";
 Target t=null;if(is(object,"net.minecraft.world.level.block.entity.BlockEntity")){Object l=R.call(object,"getLevel");if(l!=null&&!client(l))t=target(l,R.call(object,"getBlockPos"));}else if(object!=null&&object.getClass().getName().equals("de.maxhenkel.corpse.entities.CorpseEntity"))t=entityTarget(object);
 if(t!=null&&fresh(t))return "Contenido por revisar · búsqueda necesaria";
 String original=(String)R.call(interaction,"scavengingOriginalPreview",object,player);if(t==null)return original;int rarity=t.be!=null?((Number)R.call(tag(t.be),"getInt","ScavengingRarity")).intValue():History.get(t.level).tier(t.key);return "Rareza: "+Rules.name(rarity)+(original.isBlank()?"":" · "+original);
 }catch(Throwable e){warn("preview",e);return "Interactuar para revisar";}}
 public static void logout(Object event){jobs.remove(uuid(R.call(event,"getEntity")));}
 public static void clear(){jobs.clear();warned.clear();replay.remove();}
 public static void tick(){for(Job j:List.copyOf(jobs.values())){try{Target t=j.target;boolean same=t.entity!=null?!R.yes(R.call(t.entity,"isRemoved")):R.yes(R.call(t.level,"hasChunkAt",t.pos))&&t.same(target(t.level,t.pos));double d=R.num(R.call(j.player,"distanceToSqr",j.x,j.y,j.z));boolean valid=Rules.valid(now(t.level)-j.start,j.ticks,d<=.64,same,level(j.player)==t.level,R.get(j.player,"containerMenu")==R.get(j.player,"inventoryMenu"))&&eligible(j.player)&&((Number)R.get(j.player,"hurtTime")).intValue()==0&&inReach(j);
 if(!valid){message(j.player,"Búsqueda interrumpida");jobs.remove(uuid(j.player));continue;}
 int elapsed=(int)(now(t.level)-j.start);if(elapsed>=j.ticks){jobs.remove(uuid(j.player));if(fresh(t))finish(j);else open(j);}else if(elapsed%4==0){if(elapsed>0&&elapsed%8==0)sound(t,"ITEM_BUNDLE_INSERT",.45f);message(j.player,"Buscando "+Math.min(100,elapsed*100/j.ticks)+"% · Scavenging "+j.skill);}
 }catch(Throwable e){jobs.remove(uuid(j.player));warn("search tick",e);}}}
 static boolean inReach(Job j){Object t=j.target.entity;if(t!=null)return R.num(R.call(j.player,"distanceToSqr",t))<=Math.pow(R.num(R.call(j.player,"entityInteractionRange")),2);return R.num(R.call(j.player,"distanceToSqr",R.coord(j.target.pos,"X")+.5,R.coord(j.target.pos,"Y")+.5,R.coord(j.target.pos,"Z")+.5))<=Math.pow(R.num(R.call(j.player,"blockInteractionRange")),2);}
 static boolean open(Job j){replay.set(true);try{if(j.target.entity!=null)R.call(j.player,"interactOn",j.target.entity,main());else {boolean sneaking=R.yes(R.call(j.player,"isShiftKeyDown"));if(sneaking)R.call(type("cn.kafei.SilentMenuState"),"beginSilentOpen");R.call(j.player,"setShiftKeyDown",false);try{R.call(R.get(j.player,"gameMode"),"useItemOn",j.player,j.target.level,R.call(j.player,"getMainHandItem"),main(),j.hit);}finally{R.call(j.player,"setShiftKeyDown",sneaking);if(sneaking)R.call(type("cn.kafei.SilentMenuState"),"endSilentOpen");}}
 return R.get(j.player,"containerMenu")!=R.get(j.player,"inventoryMenu");}finally{replay.set(false);}}
 static void finish(Job j){if(!open(j))return;Target t=j.target;int tier=Rules.rarity(random(j.player),luck(j.player),j.skill);if(t.corpse!=null)tier=Math.max(tier,Math.max(0,Math.min(4,((Number)R.get(t.corpse,"quality")).intValue())));mark(t,tier);Loot.bonus(t,j.player,tier,j.skill);if(!R.yes(R.call(j.player,"isCreative"))){Object skills=type("dev.survivorcreator.skills.Skills"),s=R.call(skills,"get","scavenging");if(s!=null)R.call(skills,"addXp",j.player,s,Rules.xp(tier,t.corpse!=null||t.entity!=null));}sound(t,"ITEM_BUNDLE_REMOVE_ONE",.7f);message(j.player,"Hallazgo "+Rules.name(tier)+" · Scavenging "+skill(j.player));if(t.be!=null&&Rules.upgrade(tier,0))Loot.upgrade(j,tier);}
 static double random(Object p){return R.num(R.call(R.call(p,"getRandom"),"nextDouble"));}
 static void sound(Target t,String name,float volume){try{String id=switch(name){case "ITEM_BUNDLE_INSERT"->"item.bundle.insert";case "ITEM_BUNDLE_REMOVE_ONE"->"item.bundle.remove_one";default->"block.amethyst_block.chime";};Object sound=R.call(R.get(type("net.minecraft.core.registries.BuiltInRegistries"),"SOUND_EVENT"),"get",R.call(type("net.minecraft.resources.ResourceLocation"),"parse",id));if(sound==null)return;R.call(t.level,"playSound",null,t.pos,sound,R.get(type("net.minecraft.sounds.SoundSource"),"BLOCKS"),volume,1f);}catch(Throwable e){warn("sound",e);}}
 static final class Target {final Object level,pos,be,corpse,entity;final String key,hint;Target(Object l,Object p,Object b,Object c,Object e,String k){level=l;pos=p;be=b;corpse=c;entity=e;key=k;String table="";if(is(b,"net.minecraft.world.RandomizableContainer")){Object loot=R.call(b,"getLootTable");if(loot!=null)table=loot.toString();}hint=table;}boolean same(Target t){return t!=null&&level==t.level&&key.equals(t.key)&&be==t.be&&corpse==t.corpse&&entity==t.entity;}}
 static final class Job {final Object player,hit;final Target target;final long start;final int ticks,skill;final double x,y,z;Job(Object p,Target t,Object h,long n,int s){player=p;target=t;hit=h;start=n;skill=s;ticks=Rules.ticks(s);x=R.coord(p,"X");y=R.coord(p,"Y");z=R.coord(p,"Z");}}
}
