"""Additional signature-based test doubles for food metadata, particles and mixin annotations."""
def extend(sources):
    sources.update({
'net.minecraft.nbt.Tag': 'public interface Tag {}',
'net.minecraft.nbt.CompoundTag': '''import java.util.*;public class CompoundTag implements Tag {private final Map<String,Object> values=new HashMap<>();public void putInt(String k,int v){values.put(k,v);}public int getInt(String k){return ((Number)values.getOrDefault(k,0)).intValue();}public void putLong(String k,long v){values.put(k,v);}public long getLong(String k){return ((Number)values.getOrDefault(k,0L)).longValue();}public void putDouble(String k,double v){values.put(k,v);}public double getDouble(String k){return ((Number)values.getOrDefault(k,0.0)).doubleValue();}public void putBoolean(String k,boolean v){values.put(k,v);}public boolean getBoolean(String k){return (Boolean)values.getOrDefault(k,false);}public void putString(String k,String v){values.put(k,v);}public boolean contains(String k){return values.containsKey(k);}public Tag put(String k,Tag v){return (Tag)values.put(k,v);}public CompoundTag getCompound(String k){Object value=values.get(k);return value instanceof CompoundTag tag?tag:new CompoundTag();}public void remove(String k){values.remove(k);}public boolean isEmpty(){return values.isEmpty();}public CompoundTag copy(){CompoundTag result=new CompoundTag();for(var e:values.entrySet())result.values.put(e.getKey(),e.getValue() instanceof CompoundTag t?t.copy():e.getValue());return result;}public boolean equals(Object other){return other instanceof CompoundTag t && values.equals(t.values);}public int hashCode(){return values.hashCode();}public void putItems(java.util.List<net.minecraft.world.item.ItemStack> v){values.put("Items",new ArrayList<>(v));}@SuppressWarnings("unchecked") public java.util.List<net.minecraft.world.item.ItemStack> items(){return (java.util.List<net.minecraft.world.item.ItemStack>)values.get("Items");}}''',
'net.minecraft.core.component.DataComponentType': 'public interface DataComponentType<T> {}',
'net.minecraft.world.food.FoodProperties': 'public class FoodProperties {public static final FoodProperties FOOD=new FoodProperties();}',
'net.minecraft.core.component.DataComponents': '''public class DataComponents {public static final DataComponentType<net.minecraft.world.item.component.CustomData> CUSTOM_DATA=new DataComponentType<>(){};public static final DataComponentType<net.minecraft.world.food.FoodProperties> FOOD=new DataComponentType<>(){};public static final DataComponentType<net.minecraft.network.chat.Component> CUSTOM_NAME=new DataComponentType<>(){};}''',
'net.minecraft.world.item.component.CustomData': '''import net.minecraft.nbt.CompoundTag;public class CustomData {public static final CustomData EMPTY=new CustomData(new CompoundTag());private final CompoundTag tag;private CustomData(CompoundTag t){tag=t.copy();}public static CustomData of(CompoundTag t){return new CustomData(t);}public CompoundTag copyTag(){return tag.copy();}public boolean equals(Object o){return o instanceof CustomData d && tag.equals(d.tag);}public int hashCode(){return tag.hashCode();}}''',
'net.minecraft.world.item.Item': 'public class Item {public final String name;public Item(String name){this.name=name;}}',
'net.minecraft.world.item.ItemStack': '''import net.minecraft.world.item.crafting.RecipeType;import net.minecraft.core.component.*;import java.util.*;public class ItemStack {private static final Map<String,Item> ITEMS=new HashMap<>();public static final ItemStack EMPTY=new ItemStack(0,0);private int count;private final int burn;private final Item item;private final Map<DataComponentType<?>,Object> components=new HashMap<>();public ItemStack(int count,int burn){this(count,burn,"fuel_"+burn,false);}public ItemStack(int count,int burn,String id,boolean food){this.count=count;this.burn=burn;this.item=ITEMS.computeIfAbsent(id,Item::new);if(food)components.put(DataComponents.FOOD,net.minecraft.world.food.FoodProperties.FOOD);}public Item getItem(){return item;}public boolean has(DataComponentType<?> type){return components.containsKey(type);}@SuppressWarnings("unchecked") public <T> T getOrDefault(DataComponentType<? extends T> type,T fallback){return (T)components.getOrDefault(type,fallback);}@SuppressWarnings("unchecked") public <T> T set(DataComponentType<T> type,T value){return (T)components.put(type,value);}@SuppressWarnings("unchecked") public <T> T remove(DataComponentType<? extends T> type){return (T)components.remove(type);}public int getBurnTime(RecipeType<?> r){return burn;}public ItemStack getCraftingRemainingItem(){return EMPTY;}public int getCount(){return count;}public void shrink(int n){count=Math.max(0,count-n);}public void grow(int n){count+=n;}public boolean isEmpty(){return count<=0;}public ItemStack copy(){ItemStack s=new ItemStack(count,burn,item.name,false);s.components.putAll(components);return s;}public int getMaxStackSize(){return 64;}public static boolean isSameItem(ItemStack a,ItemStack b){return a.item==b.item;}public static boolean isSameItemSameComponents(ItemStack a,ItemStack b){return isSameItem(a,b) && a.components.equals(b.components);}}''',
'dev.zomboid.survival.FoodClock': '''import net.minecraft.world.item.ItemStack;import net.minecraft.nbt.CompoundTag;import net.minecraft.core.component.DataComponents;import net.minecraft.world.item.component.CustomData;public class FoodClock {public static final String KEY="zomboid_food";public static final double LIFE=30000;public static CompoundTag data(ItemStack s){return s.getOrDefault(DataComponents.CUSTOM_DATA,CustomData.EMPTY).copyTag().getCompound(KEY);}static void save(ItemStack s,CompoundTag t){CompoundTag root=s.getOrDefault(DataComponents.CUSTOM_DATA,CustomData.EMPTY).copyTag();root.put(KEY,t);s.set(DataComponents.CUSTOM_DATA,CustomData.of(root));}public static boolean perishable(ItemStack s){return !s.isEmpty() && s.has(DataComponents.FOOD);}public static String time(double ticks){return String.valueOf((long)(ticks/20));}public static void inventory(net.minecraft.world.Container c,long tick,int rate,boolean thaw){}public static ItemStack update(ItemStack s,long tick,int rate,boolean thaw){return s;}}''',
'net.minecraft.core.particles.ParticleOptions': 'public interface ParticleOptions {}',
'net.minecraft.core.particles.SimpleParticleType': 'public class SimpleParticleType implements ParticleOptions {}',
'net.minecraft.core.particles.ParticleTypes': 'public class ParticleTypes {public static final SimpleParticleType SMOKE=new SimpleParticleType();}',
'net.minecraft.server.level.ServerLevel': '''public class ServerLevel extends net.minecraft.world.level.Level {public int particles;public <T extends net.minecraft.core.particles.ParticleOptions> int sendParticles(T type,double x,double y,double z,int count,double dx,double dy,double dz,double speed){particles+=count;return 1;}}''',
'net.minecraft.sounds.SoundEvent': 'public class SoundEvent {public static SoundEvent createVariableRangeEvent(net.minecraft.resources.ResourceLocation id){return new SoundEvent();}}',
'net.minecraft.world.entity.item.ItemEntity': 'public class ItemEntity extends net.minecraft.world.entity.Entity {}',
'org.spongepowered.asm.mixin.Mixin': 'import java.lang.annotation.*;@Retention(RetentionPolicy.RUNTIME) @Target(ElementType.TYPE) public @interface Mixin {Class<?>[] value() default {};}',
'org.spongepowered.asm.mixin.injection.At': 'import java.lang.annotation.*;@Retention(RetentionPolicy.RUNTIME) public @interface At {String value();String target() default "";}',
'org.spongepowered.asm.mixin.injection.Redirect': 'import java.lang.annotation.*;@Retention(RetentionPolicy.RUNTIME) @Target(ElementType.METHOD) public @interface Redirect {String[] method();At at();}',
'org.spongepowered.asm.mixin.injection.Inject': 'import java.lang.annotation.*;@Retention(RetentionPolicy.RUNTIME) @Target(ElementType.METHOD) public @interface Inject {String[] method();At[] at();boolean cancellable() default false;}',
'org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable': 'public class CallbackInfoReturnable<T> {public void setReturnValue(T t){}}',
    })
    sources['net.minecraft.core.registries.Registries']=sources['net.minecraft.core.registries.Registries'].replace('public class Registries {','public class Registries {public static final net.minecraft.resources.ResourceKey<net.minecraft.core.Registry<net.minecraft.sounds.SoundEvent>> SOUND_EVENT=new net.minecraft.resources.ResourceKey<>();')
    sources['net.minecraft.world.level.Level']=sources['net.minecraft.world.level.Level'].replace('public boolean isClientSide;','public boolean isClientSide;public int sounds;public net.minecraft.sounds.SoundEvent lastSound;').replace('float a,float b){}','float a,float b){sounds++;lastSound=s;}')
    # A faithful copy of the original pure freshness calculation, also loaded from the actual base JAR in tests.
    sources['dev.zomboid.survival.Freshness']='''public final class Freshness {public static State advance(State s,long now,int environment,boolean heat,boolean perishable){long dt=Math.max(0,now-s.last());int oldRate=Math.max(1,s.rate());if(dt>40 && oldRate>1)oldRate=1;double left=perishable?Math.max(0,s.left()-(double)dt/oldRate):s.left();if(left<1e-6)left=0;int cold=s.cold(),chill=s.chill();boolean frozen=s.frozen();double thaw=s.thaw();if(environment>=15){cold=1200;chill=(int)Math.min(200,(long)chill+dt);}else{cold=(int)Math.max(0,(long)cold-dt);chill=0;}if(environment==20 && chill>=200){frozen=true;thaw=1200;}else if(environment!=20 && frozen && (thaw=Math.max(0,thaw-dt*(heat?6:1)))==0){frozen=false;}return new State(left,now,environment,frozen,thaw,chill,cold);}public record State(double left,long last,int rate,boolean frozen,double thaw,int chill,int cold){}}'''
