from pathlib import Path
import sys
root=Path(sys.argv[1])
sources={
'net.minecraft.nbt.CompoundTag': '''import java.util.*; public class CompoundTag { private final Map<String,Object> values=new HashMap<>(); public void putInt(String k,int v){values.put(k,v);} public int getInt(String k){return ((Number)values.getOrDefault(k,0)).intValue();} public void putLong(String k,long v){values.put(k,v);} public long getLong(String k){return ((Number)values.getOrDefault(k,0L)).longValue();} public boolean contains(String k){return values.containsKey(k);} public void putItems(java.util.List<net.minecraft.world.item.ItemStack> v){values.put("Items",new ArrayList<>(v));} @SuppressWarnings("unchecked") public java.util.List<net.minecraft.world.item.ItemStack> items(){return (java.util.List<net.minecraft.world.item.ItemStack>)values.get("Items");} }''',
'net.minecraft.world.Container': '''import net.minecraft.world.item.ItemStack; import net.minecraft.world.entity.player.Player; public interface Container { int getContainerSize(); ItemStack getItem(int n); void setItem(int n, ItemStack s); default boolean canPlaceItem(int n,ItemStack s){return true;} default boolean stillValid(Player p){return true;} default void startOpen(Player p){} default void stopOpen(Player p){} }''',
'net.minecraft.world.SimpleContainer': '''import net.minecraft.world.item.ItemStack; public class SimpleContainer implements Container {protected final ItemStack[] items; public SimpleContainer(int n){items=new ItemStack[n]; java.util.Arrays.fill(items,ItemStack.EMPTY);} public int getContainerSize(){return items.length;} public ItemStack getItem(int n){return items[n];} public void setItem(int n,ItemStack s){items[n]=s;} }''',
'net.minecraft.world.entity.Entity': 'public class Entity {}',
'net.minecraft.world.entity.player.Player': 'public class Player extends net.minecraft.world.entity.Entity {}',
'net.minecraft.world.entity.player.Inventory': 'public class Inventory extends net.minecraft.world.SimpleContainer { public final Player player; public Inventory(Player p){super(36);player=p;} public net.minecraft.network.chat.Component getDisplayName(){return net.minecraft.network.chat.Component.literal("Inventario");} }',
'net.minecraft.world.item.ItemStack': '''import net.minecraft.world.item.crafting.RecipeType; public class ItemStack {public static final ItemStack EMPTY=new ItemStack(0,0); private int count; private final int burn; public ItemStack(int count,int burn){this.count=count;this.burn=burn;} public int getBurnTime(RecipeType<?> r){return burn;} public ItemStack getCraftingRemainingItem(){return EMPTY;} public int getCount(){return count;} public void shrink(int n){count=Math.max(0,count-n);} public void grow(int n){count+=n;} public boolean isEmpty(){return count<=0;} public ItemStack copy(){return new ItemStack(count,burn);} public int getMaxStackSize(){return 64;} public static boolean isSameItemSameComponents(ItemStack a,ItemStack b){return a.burn==b.burn;} }''',
'net.minecraft.world.item.crafting.RecipeType': 'public interface RecipeType<T> {RecipeType<Object> SMELTING=new RecipeType<>(){};}',
'net.minecraft.world.inventory.ContainerData': 'public interface ContainerData {int get(int i); void set(int i,int v); int getCount();}',
'net.minecraft.world.inventory.SimpleContainerData': 'public class SimpleContainerData implements ContainerData {private final int[] data; public SimpleContainerData(int n){data=new int[n];} public int get(int i){return data[i];} public void set(int i,int v){data[i]=v;} public int getCount(){return data.length;}}',
'net.minecraft.world.inventory.Slot': '''import net.minecraft.world.Container; import net.minecraft.world.item.ItemStack; public class Slot {public final int x,y; public final Container container; private final int index; public Slot(Container c,int i,int x,int y){container=c;index=i;this.x=x;this.y=y;} public boolean mayPlace(ItemStack s){return true;} public boolean hasItem(){return !getItem().isEmpty();} public ItemStack getItem(){return container.getItem(index);} public void setByPlayer(ItemStack s){container.setItem(index,s);} public void setChanged(){} }''',
'net.minecraft.world.inventory.AbstractContainerMenu': '''import net.minecraft.world.Container;import net.minecraft.world.entity.player.Player;import net.minecraft.world.item.ItemStack;import net.minecraft.core.NonNullList; public abstract class AbstractContainerMenu {public final NonNullList<Slot> slots=NonNullList.withSize(0,null); protected AbstractContainerMenu(MenuType<?> type,int id){} protected static void checkContainerSize(Container c,int n){if(c.getContainerSize()<n)throw new IllegalArgumentException();} protected static void checkContainerDataCount(ContainerData c,int n){if(c.getCount()<n)throw new IllegalArgumentException();} protected Slot addSlot(Slot s){slots.add(s);return s;} protected void addDataSlots(ContainerData d){} public abstract boolean stillValid(Player p);public abstract ItemStack quickMoveStack(Player p,int i);public void removed(Player p){} protected boolean moveItemStackTo(ItemStack stack,int from,int to,boolean reverse){boolean changed=false; for(int phase=0;phase<2;phase++){for(int off=0;off<to-from && !stack.isEmpty();off++){Slot s=slots.get(reverse?to-1-off:from+off); if(!s.mayPlace(stack))continue; ItemStack current=s.getItem(); if(phase==0 && !current.isEmpty() && ItemStack.isSameItemSameComponents(stack,current)){int move=Math.min(stack.getCount(),64-current.getCount()); if(move>0){current.grow(move);stack.shrink(move);changed=true;}} else if(phase==1 && current.isEmpty()){int move=Math.min(64,stack.getCount()); ItemStack copy=stack.copy();copy.shrink(copy.getCount()-move);s.setByPlayer(copy);stack.shrink(move);changed=true;}}}return changed;} }''',
'net.minecraft.world.inventory.MenuType': '''import net.minecraft.world.entity.player.Inventory;import net.minecraft.world.flag.FeatureFlagSet;public class MenuType<T extends AbstractContainerMenu> { public interface MenuSupplier<T extends AbstractContainerMenu>{T create(int id,Inventory inventory);} private final MenuSupplier<T> supplier; public MenuType(MenuSupplier<T> supplier,FeatureFlagSet flags){this.supplier=supplier;} public T create(int id,Inventory inv){return supplier.create(id,inv);} }''',
'net.minecraft.world.inventory.ChestMenu': '''import net.minecraft.world.Container;import net.minecraft.world.entity.player.Inventory;import net.minecraft.world.entity.player.Player;import net.minecraft.world.item.ItemStack;public class ChestMenu extends AbstractContainerMenu {public ChestMenu(){super(null,0);}public static ChestMenu sixRows(int id,Inventory inv,Container c){return new ChestMenu();} public boolean stillValid(Player p){return true;}public ItemStack quickMoveStack(Player p,int i){return ItemStack.EMPTY;} }''',
'net.minecraft.world.flag.FeatureFlagSet': 'public class FeatureFlagSet {}',
'net.minecraft.world.flag.FeatureFlags': 'public class FeatureFlags {public static final FeatureFlagSet DEFAULT_FLAGS=new FeatureFlagSet();}',
'net.minecraft.core.Registry': 'public interface Registry<T> {}',
'net.minecraft.resources.ResourceKey': 'public final class ResourceKey<T> {}',
'net.minecraft.resources.ResourceLocation': 'public final class ResourceLocation {public static ResourceLocation fromNamespaceAndPath(String a,String b){return new ResourceLocation();}}',
'net.minecraft.core.registries.Registries': 'public class Registries {public static final net.minecraft.resources.ResourceKey<net.minecraft.core.Registry<net.minecraft.world.inventory.MenuType<?>>> MENU=new net.minecraft.resources.ResourceKey<>();}',
'net.neoforged.bus.api.SubscribeEvent': 'import java.lang.annotation.*; @Retention(RetentionPolicy.RUNTIME) @Target(ElementType.METHOD) public @interface SubscribeEvent {}',
'net.neoforged.api.distmarker.Dist': 'public enum Dist {CLIENT, DEDICATED_SERVER}',
'net.neoforged.fml.common.EventBusSubscriber': 'import java.lang.annotation.*;import net.neoforged.api.distmarker.Dist; @Retention(RetentionPolicy.RUNTIME) @Target(ElementType.TYPE) public @interface EventBusSubscriber {String modid();Dist[] value() default {Dist.CLIENT,Dist.DEDICATED_SERVER};Bus bus() default Bus.GAME;public enum Bus {GAME,MOD}}',
'net.neoforged.neoforge.registries.RegisterEvent': 'import java.util.function.Supplier;import net.minecraft.core.Registry;import net.minecraft.resources.*;public class RegisterEvent {public <T> void register(ResourceKey<? extends Registry<T>> key,ResourceLocation name,Supplier<T> value){value.get();}}',
'net.minecraft.network.chat.Component': 'public class Component {private String text;public static Component literal(String text){Component c=new Component();c.text=text;return c;}public String getString(){return text;}}',
'net.minecraft.client.gui.Font': 'public class Font {}',
'net.minecraft.client.gui.GuiGraphics': '''import net.minecraft.network.chat.Component;public class GuiGraphics {public final java.util.List<String> labels=new java.util.ArrayList<>();public int fills;public void fill(int a,int b,int c,int d,int color){if(c<a || d<b)throw new AssertionError("Bad rectangle");fills++;} public int drawString(Font font,String text,int x,int y,int color,boolean shadow){labels.add(text);return text.length()*6;} public int drawString(Font font,Component text,int x,int y,int color,boolean shadow){return drawString(font,text.getString(),x,y,color,shadow);} }''',
'net.minecraft.client.gui.screens.Screen': 'public abstract class Screen {protected net.minecraft.client.gui.Font font=new net.minecraft.client.gui.Font();protected Screen(net.minecraft.network.chat.Component c){} public void render(net.minecraft.client.gui.GuiGraphics g,int x,int y,float f){} }',
'net.minecraft.client.gui.screens.inventory.MenuAccess': 'public interface MenuAccess<T extends net.minecraft.world.inventory.AbstractContainerMenu> {T getMenu();}',
'net.minecraft.client.gui.screens.inventory.AbstractContainerScreen': '''import net.minecraft.client.gui.GuiGraphics;import net.minecraft.client.gui.screens.Screen;import net.minecraft.world.inventory.AbstractContainerMenu;import net.minecraft.world.entity.player.Inventory;import net.minecraft.network.chat.Component;public abstract class AbstractContainerScreen<T extends AbstractContainerMenu> extends Screen implements MenuAccess<T> {protected int imageWidth=176,imageHeight=166,leftPos,topPos;protected final T menu;protected final Component playerInventoryTitle;public AbstractContainerScreen(T m,Inventory i,Component c){super(c);menu=m;playerInventoryTitle=i.getDisplayName();}public T getMenu(){return menu;}public void render(GuiGraphics g,int x,int y,float f){renderBg(g,f,x,y);renderLabels(g,x,y);}protected void renderTooltip(GuiGraphics g,int x,int y){}protected abstract void renderBg(GuiGraphics g,float f,int x,int y);protected void renderLabels(GuiGraphics g,int x,int y){} }''',
'net.minecraft.client.gui.screens.MenuScreens': '''import net.minecraft.world.inventory.AbstractContainerMenu;import net.minecraft.world.entity.player.Inventory;import net.minecraft.network.chat.Component;import net.minecraft.client.gui.screens.inventory.MenuAccess;public class MenuScreens {public interface ScreenConstructor<T extends AbstractContainerMenu,U extends Screen & MenuAccess<T>> {U create(T menu,Inventory inventory,Component title);}}''',
'net.neoforged.neoforge.client.event.RegisterMenuScreensEvent': '''import net.minecraft.client.gui.screens.*;import net.minecraft.client.gui.screens.inventory.MenuAccess;import net.minecraft.world.inventory.*;public class RegisterMenuScreensEvent {public <M extends AbstractContainerMenu,U extends Screen & MenuAccess<M>> void register(MenuType<? extends M> t,MenuScreens.ScreenConstructor<M,U> s){} }''',
'net.minecraft.core.NonNullList': 'import java.util.ArrayList;public class NonNullList<E> extends ArrayList<E> {public static <E> NonNullList<E> withSize(int n,E value){NonNullList<E> list=new NonNullList<>();for(int i=0;i<n;i++)list.add(value);return list;}}',
'net.minecraft.core.Vec3i': 'public class Vec3i {protected final int x,y,z;public Vec3i(int x,int y,int z){this.x=x;this.y=y;this.z=z;}public int getX(){return x;}public int getY(){return y;}public int getZ(){return z;}public double distSqr(Vec3i p){return (double)(x-p.x)*(x-p.x)+(double)(y-p.y)*(y-p.y)+(double)(z-p.z)*(z-p.z);}public int hashCode(){return java.util.Objects.hash(x,y,z);}public boolean equals(Object o){return o instanceof Vec3i p && x==p.x && y==p.y && z==p.z;}}',
'net.minecraft.core.BlockPos': 'public class BlockPos extends Vec3i {public BlockPos(int x,int y,int z){super(x,y,z);}}',
'net.minecraft.core.HolderLookup': 'public interface HolderLookup {public interface Provider {}}',
'net.minecraft.world.level.block.Block': 'public class Block {}',
'net.minecraft.world.level.block.state.BlockState': 'public class BlockState {private final net.minecraft.world.level.block.Block block;public BlockState(net.minecraft.world.level.block.Block b){block=b;}public net.minecraft.world.level.block.Block getBlock(){return block;}}',
'net.minecraft.world.level.block.entity.BlockEntityType': 'public class BlockEntityType<T extends BlockEntity> {}',
'net.minecraft.world.level.block.entity.BlockEntity': '''import net.minecraft.core.BlockPos;import net.minecraft.world.level.Level;import net.minecraft.world.level.block.state.BlockState;public class BlockEntity {protected Level level;protected final BlockPos worldPosition;private final BlockState state;public BlockEntity(BlockEntityType<?> t,BlockPos p,BlockState s){worldPosition=p;state=s;}public void setLevel(Level l){level=l;}public BlockState getBlockState(){return state;}public void setChanged(){}public void onLoad(){}public void setRemoved(){}protected void saveAdditional(net.minecraft.nbt.CompoundTag t,net.minecraft.core.HolderLookup.Provider p){}protected void loadAdditional(net.minecraft.nbt.CompoundTag t,net.minecraft.core.HolderLookup.Provider p){} }''',
'net.minecraft.world.level.block.entity.RandomizableContainerBlockEntity': '''import net.minecraft.core.*;import net.minecraft.world.*;import net.minecraft.world.entity.player.Inventory;import net.minecraft.world.inventory.AbstractContainerMenu;import net.minecraft.world.item.ItemStack;import net.minecraft.world.level.block.state.BlockState;public abstract class RandomizableContainerBlockEntity extends BlockEntity implements Container {protected RandomizableContainerBlockEntity(BlockEntityType<?> t,BlockPos p,BlockState s){super(t,p,s);}protected abstract NonNullList<ItemStack> getItems();protected abstract void setItems(NonNullList<ItemStack> list);protected abstract net.minecraft.network.chat.Component getDefaultName();protected abstract AbstractContainerMenu createMenu(int id,Inventory inv);public ItemStack getItem(int n){return getItems().get(n);}public void setItem(int n,ItemStack s){getItems().set(n,s);}public ItemStack removeItem(int slot,int n){ItemStack old=getItem(slot);ItemStack result=old.copy();result.shrink(Math.max(0,result.getCount()-n));old.shrink(n);return result;}public ItemStack removeItemNoUpdate(int n){ItemStack s=getItem(n);setItem(n,ItemStack.EMPTY);return s;} }''',
'net.minecraft.world.level.Level': '''import java.util.*;import net.minecraft.core.BlockPos;import net.minecraft.world.level.block.entity.BlockEntity;import net.minecraft.sounds.*;import net.minecraft.world.entity.player.Player;public class Level {public boolean isClientSide;private long tick;private final Map<BlockPos,BlockEntity> entities=new HashMap<>();public long getGameTime(){return tick;}public void advance(){tick++;}public boolean hasChunkAt(BlockPos p){return entities.containsKey(p);}public BlockEntity getBlockEntity(BlockPos p){return entities.get(p);}public void add(BlockPos p,BlockEntity b){entities.put(p,b);b.setLevel(this);b.onLoad();}public void playSound(Player p,BlockPos pos,SoundEvent s,SoundSource src,float a,float b){} }''',
'net.minecraft.sounds.SoundEvent': 'public class SoundEvent {}',
'net.minecraft.sounds.SoundSource': 'public enum SoundSource {BLOCKS}',
'net.minecraft.sounds.SoundEvents': 'public class SoundEvents {public static final SoundEvent BLASTFURNACE_FIRE_CRACKLE=new SoundEvent(),BEACON_AMBIENT=new SoundEvent();}',
'net.minecraft.world.ContainerHelper': '''import net.minecraft.core.*;import net.minecraft.world.item.ItemStack;import net.minecraft.nbt.CompoundTag;public class ContainerHelper {public static CompoundTag saveAllItems(CompoundTag t,NonNullList<ItemStack> items,HolderLookup.Provider p){t.putItems(items);return t;}public static void loadAllItems(CompoundTag t,NonNullList<ItemStack> items,HolderLookup.Provider p){if(t.items()!=null){for(int i=0;i<items.size();i++)items.set(i,t.items().get(i).copy());}}}''',
'net.minecraft.world.Containers': 'public class Containers {public static void dropItemStack(net.minecraft.world.level.Level l,double x,double y,double z,net.minecraft.world.item.ItemStack s){}}',
'net.neoforged.neoforge.energy.IEnergyStorage': 'public interface IEnergyStorage {int receiveEnergy(int n,boolean sim);int extractEnergy(int n,boolean sim);int getEnergyStored();int getMaxEnergyStored();boolean canExtract();boolean canReceive();}',
'net.neoforged.neoforge.registries.DeferredHolder': 'public class DeferredHolder<R,T> {private final T value;public DeferredHolder(T t){value=t;}public T get(){return value;}}',
'dev.zomboid.survival.Survival': 'public class Survival {public static final net.neoforged.neoforge.registries.DeferredHolder<net.minecraft.world.level.block.entity.BlockEntityType<?>,net.minecraft.world.level.block.entity.BlockEntityType<MachineEntity>> MACHINES=new net.neoforged.neoforge.registries.DeferredHolder<>(new net.minecraft.world.level.block.entity.BlockEntityType<>());}',
'dev.zomboid.survival.MachineBlock': 'public class MachineBlock extends net.minecraft.world.level.block.Block {public final String machineId;public MachineBlock(String id){machineId=id;}}',
'dev.zomboid.survival.FoodClock': 'public class FoodClock {public static String time(double ticks){return String.valueOf((long)(ticks/20));}public static void inventory(net.minecraft.world.Container c,long tick,int rate,boolean thaw){}public static net.minecraft.world.item.ItemStack update(net.minecraft.world.item.ItemStack s,long tick,int rate,boolean thaw){return s;}}',
'dev.zomboid.survival.MachineEntity': '''public class MachineEntity implements net.minecraft.world.Container {public int zsFuelCarry,zsFuelTotal;public int zsGetBurn(){return 0;}public void zsSetBurn(int b){}public int zsGetEnergy(){return 0;}public boolean generator(){return true;}public int getContainerSize(){return 54;}public net.minecraft.world.item.ItemStack getItem(int n){return net.minecraft.world.item.ItemStack.EMPTY;}public void setItem(int n,net.minecraft.world.item.ItemStack s){} }''',
}
sources['dev.zomboid.survival.MachineEntity']=sources['dev.zomboid.survival.MachineEntity'].replace('implements net.minecraft.world.Container','extends net.minecraft.world.level.block.entity.BlockEntity implements net.minecraft.world.Container').replace('public int zsFuelCarry','public MachineEntity(){super(null,null,null);}public int zsFuelCarry')
sources['net.minecraft.network.chat.Component']='public interface Component {static MutableComponent literal(String text){return new MutableComponent(text);} String getString();}'
sources['net.minecraft.network.chat.MutableComponent']='public class MutableComponent implements Component {private final String text;public MutableComponent(String text){this.text=text;}public String getString(){return text;}}'
sources['net.minecraft.core.NonNullList']=sources['net.minecraft.core.NonNullList'].replace('extends ArrayList<E> {','extends ArrayList<E> {private static final long serialVersionUID=1L;')
from food_api_doubles import extend
extend(sources)
from water_api_doubles import extend as water_extend
water_extend(sources)
for name,body in sources.items():
 p=root.joinpath(*name.split('.')).with_suffix('.java');p.parent.mkdir(parents=True,exist_ok=True);p.write_text('package '+name.rsplit('.',1)[0]+';\n'+body+'\n')
print('Created',len(sources),'API test doubles; none are bundled in the mod.')
