"""Test doubles for the public API signatures already used by the original mod's water path."""
def extend(sources):
    sources.update({
'net.minecraft.world.level.ItemLike': 'public interface ItemLike {net.minecraft.world.item.Item asItem();}',
'net.minecraft.world.item.Item': '''public class Item implements net.minecraft.world.level.ItemLike {public final String name;public Item(String name){this.name=name;}public Item(Properties p){this.name="custom_"+System.identityHashCode(this);}public Item asItem(){return this;}public static class Properties {public Properties stacksTo(int n){return this;}}}''',
'net.minecraft.world.item.BlockItem': 'public class BlockItem extends Item {private final net.minecraft.world.level.block.Block block;public BlockItem(net.minecraft.world.level.block.Block b,Properties p){super(p);block=b;}public net.minecraft.world.level.block.Block getBlock(){return block;}}',
'net.minecraft.world.item.Items': '''public class Items {public static final Item WATER_BUCKET=new Item("water_bucket"),BUCKET=new Item("bucket"),GLASS_BOTTLE=new Item("glass_bottle");}''',
'net.neoforged.neoforge.registries.DeferredItem': 'public class DeferredItem<T extends net.minecraft.world.item.Item> extends DeferredHolder<net.minecraft.world.item.Item,T> {public DeferredItem(T item){super(item);}}',
'net.neoforged.neoforge.registries.DeferredBlock': 'public class DeferredBlock<T extends net.minecraft.world.level.block.Block> extends DeferredHolder<net.minecraft.world.level.block.Block,T> {public DeferredBlock(T block){super(block);}}',
'net.mcreator.doomsdaydecoration.DoomsdayDecorationMod': 'public class DoomsdayDecorationMod {public static final java.util.Map<String,net.neoforged.neoforge.registries.DeferredBlock<?>> BLOCKS_BY_ID=new java.util.HashMap<>();}',
'dev.zomboid.survival.DrinkItem': 'public final class DrinkItem extends net.minecraft.world.item.Item {public DrinkItem(Properties p,int water,float saturation){super(p);}}',
'net.minecraft.world.InteractionHand': 'public enum InteractionHand {MAIN_HAND,OFF_HAND}',
'net.minecraft.world.InteractionResult': 'public enum InteractionResult {SUCCESS,CONSUME,PASS,FAIL;public static InteractionResult sidedSuccess(boolean client){return client?SUCCESS:CONSUME;}}',
'net.minecraft.world.InteractionResultHolder': 'public class InteractionResultHolder<T> {public final T object;public final InteractionResult result;private InteractionResultHolder(T obj,InteractionResult res){object=obj;result=res;}public static <T> InteractionResultHolder<T> fail(T obj){return new InteractionResultHolder<>(obj,InteractionResult.FAIL);}public static <T> InteractionResultHolder<T> consume(T obj){return new InteractionResultHolder<>(obj,InteractionResult.CONSUME);}}',
'net.minecraft.world.entity.LivingEntity': 'public class LivingEntity extends Entity {}',
'net.minecraft.world.entity.player.Abilities': 'public class Abilities {public boolean instabuild;}',
'net.minecraft.world.entity.player.Player': '''public class Player extends net.minecraft.world.entity.LivingEntity {private net.minecraft.world.level.Level level=new net.minecraft.world.level.Level();private final Inventory inventory=new Inventory(this);private final Abilities abilities=new Abilities();private final java.util.Map<net.minecraft.world.InteractionHand,net.minecraft.world.item.ItemStack> hands=new java.util.EnumMap<>(net.minecraft.world.InteractionHand.class);public final java.util.List<String> messages=new java.util.ArrayList<>();public void displayClientMessage(net.minecraft.network.chat.Component text,boolean bar){messages.add(text.getString());}public net.minecraft.world.item.ItemStack getItemInHand(net.minecraft.world.InteractionHand hand){return hands.getOrDefault(hand,net.minecraft.world.item.ItemStack.EMPTY);}public void setItemInHand(net.minecraft.world.InteractionHand hand,net.minecraft.world.item.ItemStack stack){hands.put(hand,stack);}public Inventory getInventory(){return inventory;}public Abilities getAbilities(){return abilities;}public net.minecraft.world.entity.item.ItemEntity drop(net.minecraft.world.item.ItemStack stack,boolean random){return new net.minecraft.world.entity.item.ItemEntity();}public net.minecraft.world.level.Level level(){return level;}public void setLevel(net.minecraft.world.level.Level l){level=l;}public net.minecraft.world.phys.Vec3 getEyePosition(){return new net.minecraft.world.phys.Vec3(0,1,0);}public net.minecraft.world.phys.Vec3 getLookAngle(){return new net.minecraft.world.phys.Vec3(1,0,0);}public void startUsingItem(net.minecraft.world.InteractionHand hand){} }''',
'net.minecraft.server.level.ServerPlayer': 'public class ServerPlayer extends net.minecraft.world.entity.player.Player {}',
'net.minecraft.world.item.UseAnim': 'public enum UseAnim {DRINK}',
'homeostatic.common.Hydration': 'public class Hydration {public final int water;public Hydration(int water,float saturation,int a,int b,float c){this.water=water;}}',
'homeostatic.util.WaterHelper': 'public class WaterHelper {public static int hydrated;public static void drink(net.minecraft.server.level.ServerPlayer p,homeostatic.common.Hydration hydration,boolean b){hydrated+=hydration.water;}}',
'net.minecraft.tags.TagKey': 'public class TagKey<T> {}',
'net.minecraft.world.level.material.Fluid': 'public class Fluid {}',
'net.minecraft.tags.FluidTags': 'public class FluidTags {public static final TagKey<net.minecraft.world.level.material.Fluid> WATER=new TagKey<>();}',
'net.minecraft.world.level.material.FluidState': 'public class FluidState {public boolean is(net.minecraft.tags.TagKey<Fluid> tag){return true;}}',
'net.minecraft.world.phys.Vec3': 'public class Vec3 {public final double x,y,z;public Vec3(double x,double y,double z){this.x=x;this.y=y;this.z=z;}public Vec3 add(Vec3 v){return new Vec3(x+v.x,y+v.y,z+v.z);}public Vec3 scale(double k){return new Vec3(x*k,y*k,z*k);}}',
'net.minecraft.world.phys.HitResult': 'public class HitResult {public enum Type {MISS,BLOCK,ENTITY}public Type getType(){return Type.BLOCK;}}',
'net.minecraft.world.phys.BlockHitResult': 'public class BlockHitResult extends HitResult {public net.minecraft.core.BlockPos getBlockPos(){return new net.minecraft.core.BlockPos(0,0,0);}}',
'net.minecraft.world.level.ClipContext': 'public class ClipContext {public enum Block {OUTLINE}public enum Fluid {SOURCE_ONLY}public ClipContext(net.minecraft.world.phys.Vec3 from,net.minecraft.world.phys.Vec3 to,Block block,Fluid fluid,net.minecraft.world.entity.Entity e){}}',
'net.neoforged.neoforge.event.entity.player.PlayerInteractEvent': '''public class PlayerInteractEvent {public static class RightClickItem {private final net.minecraft.world.entity.player.Player player;private final net.minecraft.world.InteractionHand hand;public boolean canceled;public net.minecraft.world.InteractionResult result;public RightClickItem(net.minecraft.world.entity.player.Player p,net.minecraft.world.InteractionHand h){player=p;hand=h;}public net.minecraft.world.item.ItemStack getItemStack(){return player.getItemInHand(hand);}public net.minecraft.world.entity.player.Player getEntity(){return player;}public net.minecraft.world.InteractionHand getHand(){return hand;}public void setCanceled(boolean value){canceled=value;}public void setCancellationResult(net.minecraft.world.InteractionResult value){result=value;}}}''',
    })
    sources['dev.zomboid.survival.MachineEntity']=sources['dev.zomboid.survival.MachineEntity'].replace('public int zsFuelCarry,zsFuelTotal;','public int zsFuelCarry,zsFuelTotal,zsRawWater,zsCleanWater,zsWaterProgress;public String id(){return "generator";}public boolean freezer(){return false;}public boolean oven(){return false;}public boolean zsPowered(){return false;}')
    sources['dev.zomboid.survival.Survival']=sources['dev.zomboid.survival.Survival'].replace('public class Survival {','public class Survival {public static final net.neoforged.neoforge.registries.DeferredItem<net.minecraft.world.item.Item> EMPTY=new net.neoforged.neoforge.registries.DeferredItem<>(new net.minecraft.world.item.Item("empty_bottle"));public static final net.neoforged.neoforge.registries.DeferredItem<DrinkItem> WATER=new net.neoforged.neoforge.registries.DeferredItem<>(new DrinkItem(new net.minecraft.world.item.Item.Properties(),6,0.6f));')
    sources['net.minecraft.world.item.ItemStack']=sources['net.minecraft.world.item.ItemStack'].replace('public int getBurnTime','public ItemStack(net.minecraft.world.level.ItemLike item){this(item,1);}public ItemStack(net.minecraft.world.level.ItemLike item,int count){this.count=count;this.burn=0;this.item=item.asItem();}public boolean is(Item item){return this.item==item;}public int getBurnTime').replace('s.components.putAll(components);','s.item=this.item;s.components.putAll(components);').replace('private final Item item;','private Item item;')
    sources['net.minecraft.world.entity.player.Inventory']=sources['net.minecraft.world.entity.player.Inventory'].replace('public net.minecraft.network.chat.Component','public boolean add(net.minecraft.world.item.ItemStack stack){for(int i=0;i<getContainerSize();i++)if(getItem(i).isEmpty()){setItem(i,stack);return true;}return false;}public net.minecraft.network.chat.Component')
    sources['net.minecraft.world.level.Level']=sources['net.minecraft.world.level.Level'].replace('public long getGameTime()', 'public net.minecraft.world.phys.BlockHitResult clip(ClipContext context){return new net.minecraft.world.phys.BlockHitResult();}public net.minecraft.world.level.material.FluidState getFluidState(BlockPos pos){return new net.minecraft.world.level.material.FluidState();}public long getGameTime()')
    sources['net.neoforged.neoforge.registries.RegisterEvent']=sources['net.neoforged.neoforge.registries.RegisterEvent'].replace('public <T>','public net.minecraft.resources.ResourceKey<? extends net.minecraft.core.Registry<?>> getRegistryKey(){return net.minecraft.core.registries.Registries.ITEM;}public <T>')
    sources['net.minecraft.core.registries.Registries']=sources['net.minecraft.core.registries.Registries'].replace('public class Registries {','public class Registries {public static final net.minecraft.resources.ResourceKey<net.minecraft.core.Registry<net.minecraft.world.item.Item>> ITEM=new net.minecraft.resources.ResourceKey<>();')
    sources['dev.zomboid.survival.FoodClock']=sources['dev.zomboid.survival.FoodClock'].replace('public static boolean perishable','public static boolean cold(ItemStack s){return data(s).getInt("cold")>0;}public static boolean frozen(ItemStack s){return data(s).getBoolean("frozen");}public static boolean perishable')
