import java.nio.file.*;import java.util.*;import java.util.zip.*;import org.objectweb.asm.*;import org.objectweb.asm.tree.*;import org.objectweb.asm.tree.analysis.*;
public final class Patch implements Opcodes {
 static final String SEARCH="dev/zomboid/scavenging/Search";
 static byte[] edit(byte[] bytes,String name){ClassNode c=new ClassNode();new ClassReader(bytes).accept(c,0);int count=0;
 if(c.name.equals("cn/kafei/interact/Interaction")){MethodNode original=c.methods.stream().filter(m->m.name.equals("preview")).findFirst().orElseThrow();original.name="scavengingOriginalPreview";MethodNode wrapper=new MethodNode(ACC_PUBLIC|ACC_STATIC,"preview",original.desc,null,null);wrapper.instructions.add(new VarInsnNode(ALOAD,0));wrapper.instructions.add(new VarInsnNode(ALOAD,1));wrapper.instructions.add(new MethodInsnNode(INVOKESTATIC,SEARCH,"preview","(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/String;",false));wrapper.instructions.add(new InsnNode(ARETURN));c.methods.add(wrapper);count++;}
 for(MethodNode m:c.methods){
 if(c.name.equals("snownee/jade/addon/universal/ItemStorageProvider")&&m.name.equals("putData")){InsnList h=new InsnList();h.add(new VarInsnNode(ALOAD,0));h.add(new MethodInsnNode(INVOKESTATIC,"dev/zomboid/scavengingjade/Bridge","hide","(Ljava/lang/Object;)Z",false));LabelNode pass=new LabelNode();h.add(new JumpInsnNode(IFEQ,pass));h.add(new VarInsnNode(ALOAD,0));h.add(new MethodInsnNode(INVOKEINTERFACE,"snownee/jade/api/Accessor","getServerData","()Lnet/minecraft/nbt/CompoundTag;",true));h.add(new LdcInsnNode("Loot"));h.add(new InsnNode(ICONST_1));h.add(new MethodInsnNode(INVOKEVIRTUAL,"net/minecraft/nbt/CompoundTag","putBoolean","(Ljava/lang/String;Z)V",false));h.add(new InsnNode(RETURN));h.add(pass);h.add(new FrameNode(F_SAME,0,null,0,null));m.instructions.insert(h);count++;}
 if(c.name.equals("cn/kafei/QuietlyCommon")&&m.name.equals("shouldCancelVanillaUse")){InsnList h=new InsnList();h.add(new MethodInsnNode(INVOKESTATIC,SEARCH,"replaying","()Z",false));LabelNode pass=new LabelNode();h.add(new JumpInsnNode(IFEQ,pass));h.add(new InsnNode(ICONST_0));h.add(new InsnNode(IRETURN));h.add(pass);h.add(new FrameNode(F_SAME,0,null,0,null));m.instructions.insert(h);count++;}
 if(c.name.equals("cn/kafei/SilentOpenManager")&&m.name.equals("startOrRefresh")){InsnList h=new InsnList();h.add(new VarInsnNode(ALOAD,0));h.add(new VarInsnNode(ALOAD,1));h.add(new MethodInsnNode(INVOKESTATIC,SEARCH,"shift","(Ljava/lang/Object;Ljava/lang/Object;)Z",false));LabelNode pass=new LabelNode();h.add(new JumpInsnNode(IFEQ,pass));h.add(new InsnNode(RETURN));h.add(pass);h.add(new FrameNode(F_SAME,0,null,0,null));m.instructions.insert(h);count++;}
 if(c.name.equals("cn/kafei/neoforge/QuietlyNeoForge")&&m.name.equals("onServerTick")){InsnList h=new InsnList();h.add(new MethodInsnNode(INVOKESTATIC,SEARCH,"tick","()V",false));m.instructions.insert(h);count++;}
 if(c.name.equals("dev/survivorcreator/skills/ActiveSkills")&&m.name.equals("<clinit>"))for(AbstractInsnNode n:m.instructions.toArray())if(n instanceof FieldInsnNode f&&f.getOpcode()==PUTSTATIC&&f.name.equals("IDS")){InsnList h=new InsnList();h.add(new TypeInsnNode(NEW,"java/util/ArrayList"));h.add(new InsnNode(DUP));h.add(new FieldInsnNode(GETSTATIC,c.name,"IDS","Ljava/util/List;"));h.add(new MethodInsnNode(INVOKESPECIAL,"java/util/ArrayList","<init>","(Ljava/util/Collection;)V",false));h.add(new InsnNode(DUP));h.add(new LdcInsnNode("scavenging"));h.add(new MethodInsnNode(INVOKEVIRTUAL,"java/util/ArrayList","add","(Ljava/lang/Object;)Z",false));h.add(new InsnNode(POP));h.add(new MethodInsnNode(INVOKESTATIC,"java/util/Collections","unmodifiableList","(Ljava/util/List;)Ljava/util/List;",false));h.add(new FieldInsnNode(PUTSTATIC,c.name,"IDS","Ljava/util/List;"));m.instructions.insert(n,h);count++;}
 if(c.name.equals("dev/survivorcreator/skills/Skills")&&m.name.equals("<clinit>"))for(AbstractInsnNode n:m.instructions.toArray())if(n.getOpcode()==RETURN){InsnList h=new InsnList();h.add(new LdcInsnNode("scavenging"));h.add(new FieldInsnNode(GETSTATIC,"dev/survivorcreator/skills/Skill$Category","SURVIVALIST","Ldev/survivorcreator/skills/Skill$Category;"));h.add(new InsnNode(ICONST_1));h.add(new TypeInsnNode(ANEWARRAY,"dev/survivorcreator/skills/SkillEffect"));h.add(new InsnNode(DUP));h.add(new InsnNode(ICONST_0));h.add(new TypeInsnNode(NEW,"dev/survivorcreator/skills/ScavengingEffect"));h.add(new InsnNode(DUP));h.add(new MethodInsnNode(INVOKESPECIAL,"dev/survivorcreator/skills/ScavengingEffect","<init>","()V",false));h.add(new InsnNode(AASTORE));h.add(new MethodInsnNode(INVOKESTATIC,"dev/survivorcreator/skills/Skill","active","(Ljava/lang/String;Ldev/survivorcreator/skills/Skill$Category;[Ldev/survivorcreator/skills/SkillEffect;)Ldev/survivorcreator/skills/Skill;",false));h.add(new MethodInsnNode(INVOKESTATIC,c.name,"register","(Ldev/survivorcreator/skills/Skill;)Ldev/survivorcreator/skills/Skill;",false));h.add(new InsnNode(POP));m.instructions.insertBefore(n,h);count++;}
 if(c.name.equals("dev/zomboid/survival/ClientColors"))for(AbstractInsnNode n:m.instructions.toArray())if(n instanceof LdcInsnNode x&&Integer.valueOf(-12088636).equals(x.cst)){x.cst=-1;count++;}
 }
 if(count==0)throw new IllegalStateException("No edits: "+name);ClassWriter out=new ClassWriter(ClassWriter.COMPUTE_MAXS);c.accept(out);byte[] result=out.toByteArray();verify(result);System.out.println(name+" : "+count+" edits verified");return result;
 }
 static void verify(byte[] bytes){ClassNode c=new ClassNode();new ClassReader(bytes).accept(c,0);try{for(MethodNode m:c.methods)if((m.access&(ACC_NATIVE|ACC_ABSTRACT))==0)new Analyzer<BasicValue>(new BasicVerifier()).analyze(c.name,m);}catch(Exception e){throw new IllegalStateException(c.name,e);}}
 // Every newly compiled class is checked, and no Minecraft/NeoForge test API is bundled.
 public static void main(String[] args)throws Exception {String mode=args[0];Set<String> edits=switch(mode){case "quietly"->Set.of("cn/kafei/QuietlyCommon.class","cn/kafei/SilentOpenManager.class","cn/kafei/neoforge/QuietlyNeoForge.class","cn/kafei/interact/Interaction.class");case "survivor"->Set.of("dev/survivorcreator/skills/Skills.class","dev/survivorcreator/skills/ActiveSkills.class");case "jade"->Set.of("snownee/jade/addon/universal/ItemStorageProvider.class");case "survival"->Set.of("dev/zomboid/survival/ClientColors.class");default->throw new IllegalArgumentException(mode);};Map<String,byte[]> added=new TreeMap<>();try(var paths=Files.walk(Path.of(args[3]))){for(Path p:paths.filter(Files::isRegularFile).toList()){String name=Path.of(args[3]).relativize(p).toString();byte[] b=Files.readAllBytes(p);if(name.endsWith(".class")){if(!name.startsWith("dev/"))throw new IllegalStateException("Stub would be packaged");verify(b);}added.put(name,b);}}
 try(ZipFile in=new ZipFile(args[1]);ZipOutputStream out=new ZipOutputStream(Files.newOutputStream(Path.of(args[2])))){for(var it=in.entries();it.hasMoreElements();){var e=it.nextElement();byte[] b=in.getInputStream(e).readAllBytes();if(added.containsKey(e.getName()))b=added.remove(e.getName());else if(edits.contains(e.getName()))b=edit(b,e.getName());out.putNextEntry(new ZipEntry(e.getName()));out.write(b);out.closeEntry();}for(var e:added.entrySet()){out.putNextEntry(new ZipEntry(e.getKey()));out.write(e.getValue());out.closeEntry();}}
 }
}
